# Generated by Django 6.0.1 on 2026-08-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vchno',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('TYPE', models.CharField(db_column='type', max_length=6, unique=True)),
                ('VCHNO', models.IntegerField(db_column='vchno', default=0)),
                ('REMARKS', models.CharField(blank=True, db_column='remarks', max_length=50, null=True)),
                ('JAN', models.IntegerField(db_column='jan', default=0)),
                ('FEB', models.IntegerField(db_column='feb', default=0)),
                ('MAR', models.IntegerField(db_column='mar', default=0)),
                ('APR', models.IntegerField(db_column='apr', default=0)),
                ('MAY', models.IntegerField(db_column='may', default=0)),
                ('JUN', models.IntegerField(db_column='jun', default=0)),
                ('JUL', models.IntegerField(db_column='jul', default=0)),
                ('AUG', models.IntegerField(db_column='aug', default=0)),
                ('SEP', models.IntegerField(db_column='sep', default=0)),
                ('OCT', models.IntegerField(db_column='oct', default=0)),
                ('NOV', models.IntegerField(db_column='nov', default=0)),
                ('DECE', models.IntegerField(db_column='dece', default=0)),
            ],
            options={
                'db_table': 'vchno',
            },
        ),
        migrations.CreateModel(
            name='Gledg',
            fields=[
                ('GLEDG_ID', models.AutoField(db_column='gledg_id', primary_key=True, serialize=False)),
                ('ACC_CODE', models.IntegerField(blank=True, db_column='acc_code', null=True)),
                ('REF_ACC_CODE', models.IntegerField(db_column='ref_acc_code')),
                ('ACC_HEAD', models.CharField(blank=True, db_column='acc_head', max_length=200, null=True)),
                ('V_TYPE', models.CharField(blank=True, db_column='v_type', max_length=2, null=True)),
                ('VNO', models.IntegerField(blank=True, db_column='vnao', null=True)),
                ('DATE', models.DateField(blank=True, db_column='date', null=True)),
                ('DESCRIPTION', models.CharField(blank=True, db_column='desc', max_length=60, null=True)),
                ('REMARKS', models.CharField(blank=True, db_column='remarks', max_length=60, null=True)),
                ('AMOUNT', models.DecimalField(blank=True, db_column='amount', decimal_places=2, max_digits=12, null=True)),
                ('AMT_TYPE', models.CharField(blank=True, db_column='amt_type', max_length=2, null=True)),
                ('CHQNO', models.CharField(blank=True, db_column='chqno', max_length=15, null=True)),
                ('PUR_INV', models.CharField(blank=True, db_column='Pur_Inv', default='I', help_text='R = Production, P = Purchase, I = Invoice', max_length=1, null=True)),
                ('DATEENT', models.DateTimeField(blank=True, db_column='dateent', null=True)),
                ('DATEEDIT', models.DateTimeField(blank=True, db_column='dateedit', null=True)),
                ('USER', models.CharField(blank=True, db_column='user', max_length=10, null=True)),
                ('EDITBY', models.CharField(blank=True, db_column='editby', max_length=10, null=True)),
                ('RECEIPTNO', models.IntegerField(blank=True, db_column='receiptno', null=True)),
                ('INVOICE_ID', models.IntegerField(blank=True, db_column='inv_id', null=True)),
                ('SHIFT', models.CharField(blank=True, db_column='shift', max_length=1, null=True)),
                ('CHEQUE_DATE', models.DateField(blank=True, db_column='cheque_date', null=True)),
                ('DRAWN_BRANCH', models.CharField(blank=True, db_column='drawn_branch', max_length=35, null=True)),
                ('PAYMENTMETHOD', models.CharField(blank=True, db_column='paymentmethod', max_length=12, null=True)),
                ('SHOW_IN_SALE_RPT', models.CharField(db_column='show_in_sale_rpt', default='N', max_length=1)),
                ('BANK_RECONCILE', models.CharField(blank=True, db_column='bank_reconcile', max_length=1, null=True)),
                ('ISPOSTED', models.CharField(blank=True, db_column='isposted', max_length=1, null=True)),
                ('SALES_MAN', models.CharField(blank=True, db_column='sales_man', max_length=15, null=True)),
                ('DEPT', models.CharField(blank=True, db_column='dept', max_length=25, null=True)),
                ('BRANCH', models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('COMPANY', models.ForeignKey(blank=True, db_column='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
                ('POSTERMINAL', models.ForeignKey(blank=True, db_column='terminal', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.posterminal')),
            ],
            options={
                'db_table': 'gledg',
                'indexes': [models.Index(fields=['V_TYPE', 'VNO'], name='gledg_v_type_c8c5e4_idx'), models.Index(fields=['ACC_CODE'], name='gledg_acc_cod_4e1736_idx'), models.Index(fields=['DATE'], name='gledg_date_8f35e9_idx'), models.Index(fields=['AMT_TYPE'], name='gledg_amt_typ_8099f7_idx')],
            },
        ),
    ]
