# Generated by Django 6.0.1 on 2026-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myledger', '0002_auto_20260802_1358'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gledg',
            new_name='gledg_v_type_d57195_idx',
            old_name='gledg_v_type_c8c5e4_idx',
        ),
        migrations.AlterField(
            model_name='gledg',
            name='VNO',
            field=models.IntegerField(blank=True, db_column='vno', null=True),
        ),
    ]
