# Generated by Django 6.0.1 on 2026-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
        ('myledger', '0003_rename_gledg_v_type_c8c5e4_idx_gledg_v_type_d57195_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gledg',
            name='gledg_date_8f35e9_idx',
        ),
        migrations.RenameIndex(
            model_name='gledg',
            new_name='gledg_vtype_vno_idx',
            old_name='gledg_v_type_d57195_idx',
        ),
        migrations.RenameIndex(
            model_name='gledg',
            new_name='gledg_acc_code_idx',
            old_name='gledg_acc_cod_4e1736_idx',
        ),
        migrations.RenameIndex(
            model_name='gledg',
            new_name='gledg_amt_type_idx',
            old_name='gledg_amt_typ_8099f7_idx',
        ),
        migrations.AddIndex(
            model_name='gledg',
            index=models.Index(fields=['DATE', 'DATEENT', 'GLEDG_ID'], name='gledg_daybook_idx'),
        ),
    ]
