# Generated by Django 6.0.1 on 2026-07-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='header_frieght_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='header_freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('posted', 'Posted')], default='posted', max_length=20),
        ),
    ]
