# Generated by Django 6.0.1 on 2026-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchase_header_frieght_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='header_payment_mode',
            field=models.PositiveIntegerField(blank=True, db_comment='112000001=cash , any other = card', default=112000001, null=True),
        ),
    ]
