# Generated by Django 6.0.1 on 2026-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_header_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='header_payment_mode',
            field=models.IntegerField(blank=True, db_comment='112000001=cash , any other = card', default=112000001, null=True),
        ),
    ]
