# Generated by Django 6.0.1 on 2026-07-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_header_payment_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='purchase_valid_payment_mode',
        ),
    ]
