# Generated by Django 6.0.1 on 2026-07-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_remove_purchase_purchase_valid_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='row_expire_dt',
            new_name='row_expiry_dt',
        ),
    ]
