# Generated by Django 6.0.1 on 2026-07-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_rename_row_expire_dt_purchase_row_expiry_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='row_rate_cost',
            new_name='row_total_cost',
        ),
    ]
