# Generated by Django 6.0.1 on 2026-07-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_row_rate_cost_purchase_row_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='row_total_cost',
            new_name='row_total_cost_per_base_unit',
        ),
    ]
