# Generated by Django 6.0.1 on 2026-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_rename_row_total_cost_purchase_row_total_cost_per_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='header_freight_acc_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='header_labour_acc_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='header_unload_acc_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
