# Generated by Django 6.0.1 on 2026-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchase_header_freight_acc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dateent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
