# Generated by Django 6.0.1 on 2026-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchase_dateent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='row_remaining_qty',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Remaining base_qty after sale', null=True),
        ),
    ]
