# Generated by Django 6.0.1 on 2026-06-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('ID', models.CharField(blank=True, db_column='id', max_length=1, null=True)),
                ('BRANCH_ID', models.IntegerField(blank=True, db_column='branchid', null=True)),
                ('SERIAL_NO', models.IntegerField(blank=True, db_column='serialno', null=True)),
                ('ACC_CODE', models.IntegerField(db_column='acc_code', primary_key=True, serialize=False)),
                ('FIXED_HEAD', models.CharField(blank=True, db_column='fixedhead', max_length=1, null=True)),
                ('ENABLE', models.CharField(blank=True, db_column='enable', max_length=1, null=True)),
                ('BUDGET', models.CharField(blank=True, db_column='budget', max_length=1, null=True)),
                ('ACC_NAME', models.CharField(blank=True, db_column='head', max_length=70, null=True)),
                ('ADDRESS', models.CharField(blank=True, db_column='address', max_length=80, null=True)),
                ('COUNTRY', models.CharField(blank=True, db_column='country', max_length=45, null=True)),
                ('CITY', models.CharField(blank=True, db_column='city', max_length=20, null=True)),
                ('PHONE_OFF', models.CharField(blank=True, db_column='phone_off', max_length=30, null=True)),
                ('PHONE_RES', models.CharField(blank=True, db_column='phone_res', max_length=15, null=True)),
                ('MOBILE_NO', models.CharField(blank=True, db_column='mobile_no', max_length=40, null=True)),
                ('WEB_ADDRESS', models.CharField(blank=True, db_column='web_add', max_length=40, null=True)),
                ('EMAIL_ADDRESS', models.CharField(blank=True, db_column='email_add', max_length=40, null=True)),
                ('NAME_OF_HEAD', models.CharField(blank=True, db_column='nameofhead', max_length=70, null=True)),
                ('LEVEL', models.IntegerField(blank=True, db_column='level', null=True)),
                ('TYPE', models.CharField(blank=True, db_column='type', max_length=6, null=True)),
                ('CLASS_FIELD', models.CharField(blank=True, db_column='class', max_length=18, null=True)),
                ('OPENING_BALANCE', models.FloatField(blank=True, db_column='op_balance', default=0.0, null=True)),
                ('BALANCE_TYPE', models.CharField(blank=True, db_column='bal_type', max_length=2, null=True)),
                ('REMARKS', models.TextField(blank=True, db_column='remarks', null=True)),
                ('REF_CODE', models.IntegerField(blank=True, db_column='ref_code', null=True)),
                ('CREDIT_LIMIT', models.IntegerField(blank=True, db_column='crlimit', null=True)),
                ('BANK_ACCOUNT', models.IntegerField(blank=True, db_column='bank_acct', null=True)),
                ('PICTURE', models.CharField(blank=True, db_column='pict_upload', max_length=20, null=True)),
                ('BANK_RECONCILE', models.CharField(blank=True, db_column='bank_reconcile', max_length=1, null=True)),
                ('PASSWORD', models.CharField(blank=True, db_column='acc_pwd', max_length=10, null=True)),
                ('RECONCILE_REMARKS', models.CharField(blank=True, db_column='reconcile_rmks', max_length=50, null=True)),
                ('PROFILE_DISCOUNT', models.CharField(blank=True, db_column='profile_disc', default='N', max_length=1, null=True)),
                ('SALESMAN', models.CharField(blank=True, db_column='salesman', max_length=25, null=True)),
                ('NTN_NO', models.CharField(blank=True, db_column='ntnno', max_length=35, null=True)),
                ('STN_NO', models.CharField(blank=True, db_column='stnno', max_length=35, null=True)),
                ('RECONCILE_DATE', models.DateField(blank=True, db_column='reconcile_dte', null=True)),
                ('DATEENT', models.DateTimeField(auto_now_add=True, null=True)),
                ('DATEEDIT', models.DateTimeField(auto_now=True, null=True)),
                ('USER', models.CharField(blank=True, max_length=100, null=True)),
                ('EDITBY', models.CharField(blank=True, max_length=100, null=True)),
                ('BRANCH', models.ForeignKey(blank=True, db_column='branch', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('COMPANY', models.ForeignKey(blank=True, db_column='company', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
                ('POSTERMINAL', models.ForeignKey(blank=True, db_column='terminal', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.posterminal')),
            ],
            options={
                'db_table': 'accounts',
                'indexes': [models.Index(fields=['LEVEL', 'CLASS_FIELD', 'TYPE'], name='accounts_level_e78817_idx'), models.Index(fields=['ACC_CODE'], name='accounts_acc_cod_5d64a9_idx')],
            },
        ),
    ]
