# Generated by Django 6.0.1 on 2026-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_companyconfiguration_options_and_more'),
        ('myaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['COMPANY', 'ACC_CODE'], name='idx_acc_comp_code'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['COMPANY', 'ACC_NAME'], name='idx_acc_comp_name'),
        ),
    ]
