# Generated by Django 6.0.5 on 2026-05-18 11:57
# first makemigrations --empty
# than paste this in empty migration file andn then migrate
from django.db import migrations


class Migration(migrations.Migration):
    
    def create_voucher_types(apps, schema_editor):

        VoucherType = apps.get_model(
            "myledger",
            "Vchno"
        )

        data = [

            ("CP", 0, "Cash Payment"),
            ("CR", 0, "Cash Receipt"),
            ("BP", 0, "Bank Payment"),
            ("BR", 0, "Bank Receipt"),
            ("JV", 0, "Journal Voucher"),
            ("INV", 0, "Invoice Voucher"),
            ("IRTN", 0, "Invoice Return Voucher"),
            ("PUR", 0, "Purchase Voucher"),
            ("PRTN", 0, "Purchase Return Voucher"),
            ("GSRNO", 0, "Gledg Srno"),
            ("ISRNO", 0, "Invoice Srno"),
            ("PSRNO", 0, "Purchase Srno"),

        ]

        for code, no, remarks in data:

            VoucherType.objects.get_or_create(
                TYPE=code,
                defaults={
                    "VCHNO": no,
                    "REMARKS": remarks,
                }
            )


    dependencies = [
        ('myledger', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(create_voucher_types),
    ]


