# Generated by Django 6.0.1 on 2026-06-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gledg',
            fields=[
                ('gledg_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_code', models.IntegerField(blank=True, null=True)),
                ('ref_acc_code', models.IntegerField()),
                ('v_type', models.CharField(blank=True, max_length=2, null=True)),
                ('vno', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, db_collation='latin1_general_ci', max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('amt_type', models.CharField(blank=True, max_length=2, null=True)),
                ('chqno', models.CharField(blank=True, max_length=15, null=True)),
                ('ref_no', models.IntegerField(blank=True, db_comment='computer_do_no', null=True)),
                ('dateent', models.DateTimeField(blank=True, null=True)),
                ('dateedit', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, db_collation='latin1_general_ci', max_length=10, null=True)),
                ('editby', models.CharField(blank=True, max_length=10, null=True)),
                ('branchid', models.IntegerField(blank=True, null=True)),
                ('receiptno', models.IntegerField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=1, null=True)),
                ('cheque_date', models.DateField()),
                ('drawn_branch', models.CharField(max_length=35)),
                ('paymentmethod', models.CharField(max_length=12)),
                ('upload', models.CharField(max_length=1)),
                ('show_in_sale_rpt', models.CharField(blank=True, max_length=1, null=True)),
                ('isposted', models.CharField(max_length=1)),
                ('inv_yes_no', models.CharField(max_length=1)),
                ('bank_reconcile', models.CharField(max_length=1)),
                ('actual_installment', models.IntegerField()),
                ('pur_inv', models.CharField(db_column='Pur_Inv', max_length=1)),
                ('station', models.CharField(db_collation='latin1_general_ci', max_length=5)),
                ('prod_categ', models.CharField(db_collation='latin1_general_ci', max_length=25)),
            ],
            options={
                'db_table': 'gledg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vchno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=3, null=True)),
                ('vchno', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sep', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dece', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vchno',
                'managed': False,
            },
        ),
    ]
