# Generated by Django 6.0.1 on 2026-06-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=10, null=True)),
                ('price_base', models.CharField(choices=[('N', 'Normal'), ('P', 'Pice Embeded')], max_length=1)),
                ('total_bc_digits', models.PositiveSmallIntegerField(default=13)),
                ('left_delete', models.PositiveSmallIntegerField(default=2)),
                ('right_delete', models.PositiveSmallIntegerField(default=1)),
                ('item_bc', models.PositiveSmallIntegerField(default=5)),
                ('kg', models.PositiveSmallIntegerField(default=2)),
                ('grm', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'db_table': 'ab_BarcodConfig',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='All Features', max_length=50)),
                ('pos_discount_per_item', models.BooleanField(default=True)),
                ('pos_load_prv_bill', models.BooleanField(default=True)),
                ('pos_disc_flat_limit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_no', models.IntegerField(db_index=True)),
                ('is_header', models.BooleanField(db_index=True, default=False)),
                ('header_edit_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('inv_id', models.IntegerField(blank=True, null=True)),
                ('prod_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('packing_mode', models.PositiveSmallIntegerField(blank=True, db_comment='1=base 2=ctrn 3=dzn 4=wholesale', default=1, null=True)),
                ('pack_qty', models.DecimalField(blank=True, db_comment='crtn_qty if packing mode=2, dzn_qty if packing mode=3', decimal_places=3, default=0, max_digits=12, null=True)),
                ('row_discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('row_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('row_net_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('row_notes', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('dateent', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateedit', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=150)),
                ('edit_by', models.CharField(blank=True, default='', max_length=150)),
                ('salesman', models.CharField(blank=True, default='', max_length=150)),
                ('header_total_items', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('header_item_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('header_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_delivery_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_gst_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('header_gst_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_msc_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_net_total', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_remarks', models.TextField(blank=True, default='')),
                ('header_payment_mode', models.PositiveSmallIntegerField(blank=True, db_comment='1=cash 2=bank 3=dual', default=1, null=True)),
                ('header_cash_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_bank_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('header_total_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_change_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
                ('posterminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.posterminal')),
            ],
            options={
                'db_table': 'invoice',
                'managed': True,
                'indexes': [models.Index(fields=['bill_no'], name='invoice_bill_no_70505f_idx'), models.Index(fields=['is_header'], name='invoice_is_head_b7b899_idx'), models.Index(fields=['date', 'is_header'], name='invoice_date_7fdc3c_idx'), models.Index(fields=['posterminal', 'date'], name='invoice_posterm_55ab26_idx'), models.Index(fields=['is_header', 'header_net_total'], name='invoice_is_head_4dd9d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('header_payment_mode__in', [1, 2, 3])), name='valid_payment_mode'), models.CheckConstraint(condition=models.Q(models.Q(('header_total_items__gte', 0), ('is_header', True)), models.Q(('header_total_items', 0), ('is_header', False)), _connector='OR'), name='total_items_only_on_header')],
            },
        ),
    ]
