# Generated by Django 6.0.1 on 2026-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_barcodconfig_features_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='edit_by',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='header_card_last4',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='header_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='row_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='salesman',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
