# Generated by Django 6.0.1 on 2026-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_invoice_category_alter_invoice_edit_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateedit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
