# Generated by Django 6.0.1 on 2026-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_invoice_uom_alter_invoice_dateedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='header_acc_code',
            field=models.IntegerField(blank=True, default=112000001, max_length=12, null=True),
        ),
    ]
