# Generated by Django 6.0.1 on 2026-07-01 23:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
        ('sale', '0005_invoice_header_acc_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('bill_no', models.IntegerField(db_index=True)),
                ('is_header', models.BooleanField(db_index=True, default=False)),
                ('header_edit_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('header_acc_code', models.IntegerField(blank=True, default=112000001, max_length=12, null=True)),
                ('inv_id', models.IntegerField(blank=True, null=True)),
                ('prod_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('packing_mode', models.PositiveSmallIntegerField(blank=True, db_comment='1=base 2=ctrn 3=dzn 4=wholesale', default=1, null=True)),
                ('pack_qty', models.DecimalField(blank=True, db_comment='crtn_qty if packing mode=2, dzn_qty if packing mode=3', decimal_places=3, default=0, max_digits=12, null=True)),
                ('row_discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('row_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('row_net_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('row_notes', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('dateent', models.DateTimeField(blank=True, editable=False, null=True)),
                ('dateedit', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('edit_by', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('salesman', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('header_total_items', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('header_item_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('header_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_delivery_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_gst_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('header_gst_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_msc_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_net_total', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_remarks', models.TextField(blank=True, default='', null=True)),
                ('header_payment_mode', models.PositiveSmallIntegerField(blank=True, db_comment='1=cash 2=bank 3=dual', default=1, null=True)),
                ('header_cash_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_bank_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_card_last4', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('header_total_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('header_change_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.branch')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posterminal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configuration.posterminal')),
            ],
            options={
                'verbose_name': 'historical invoice',
                'verbose_name_plural': 'historical invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
