# Generated by Django 6.0.1 on 2026-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_historicalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='header_acc_code',
            field=models.IntegerField(blank=True, default=112000001, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='header_acc_code',
            field=models.IntegerField(blank=True, default=112000001, null=True),
        ),
    ]
