# Generated by Django 6.0.1 on 2026-08-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_historicalinvoice_row_net_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gledg',
        ),
        migrations.DeleteModel(
            name='Vchno',
        ),
    ]
