# Generated by Django 6.0.1 on 2026-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_delete_gledg_delete_vchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='dateent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dateent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
