# Generated by Django 6.0.1 on 2026-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_historicalinvoice_dateent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='header_quo_con_by',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='header_quo_con_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='header_quo_con_by',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='header_quo_con_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
