# Generated by Django 6.0.1 on 2026-09-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_companyconfiguration_options_and_more'),
        ('sale', '0011_historicalinvoice_header_quo_con_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['header_quo_con_no'], name='invoice_header__89c0de_idx'),
        ),
    ]
