"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import configparser
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Locate config.ini
# ---------------------------------------------------------------------------
# When frozen by Nuitka/PyInstaller:  config.ini sits beside Software.exe
# When running normally (python manage.py ...): config.ini sits beside manage.py

if getattr(sys, 'frozen', False):
    # Nuitka sets sys.frozen = True; sys.executable is the .exe path
    _EXE_DIR = Path(sys.executable).resolve().parent
else:
    # Dev mode: config.ini is beside manage.py (project root)
    _EXE_DIR = Path(__file__).resolve().parent.parent

_CONFIG_FILE = _EXE_DIR / 'config.ini'

_cfg = configparser.ConfigParser(interpolation=None)
_cfg.read(str(_CONFIG_FILE), encoding='utf-8')

def _path(section: str, key: str, fallback: str = '') -> Path:
    """Resolve a config value as a Path. Relative values are anchored to _EXE_DIR."""
    raw = _cfg.get(section, key, fallback=fallback).strip()
    p = Path(raw)
    return p if p.is_absolute() else _EXE_DIR / p

# ---------------------------------------------------------------------------
# Build paths inside the project (used for templates, etc.)
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _cfg.get('django', 'secret_key', fallback='django-insecure-)a@m=kls@$mm327#$%pr@65nz7qpihlr_-z^_ocvr$5^6vty$w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _cfg.getboolean('django', 'debug', fallback=True)

_allowed_raw = _cfg.get('django', 'allowed_hosts', fallback='127.0.0.1,localhost')
# ALLOWED_HOSTS = [h.strip() for h in _allowed_raw.split(',') if h.strip()]
ALLOWED_HOSTS = ['*']



CSRF_TRUSTED_ORIGINS = [
    'https://maternal-entrap-edge.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://races-plates-store-suspension.trycloudflare.com',
    'https://*.trycloudflare.com',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# CSRF_TRUSTED_ORIGINS = [
#     'https://a1b2c3d4.ngrok-free.app',  # <--- CHANGE THIS TO YOUR LINK
#     'https://a1b2c3d4.ngrok-free.dev',  # <--- CHANGE THIS TO YOUR LINK
#     'https://*.ngrok-free.app',
#     'https://*.ngrok.io',
#     'https://*.trycloudflare.com',
#     'https://maternal-entrap-edge.ngrok-free.dev ',
# ]

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# USE_X_FORWARDED_HOST = True
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SAMESITE = 'Lax'
# SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.configuration',
    'apps.inventory',
    'apps.myaccounts',
    'apps.myledger',
    'apps.sale',
    'apps.users',
    'apps.myglobal',
    'apps.mysearch',
    'apps.purchase',
    "simple_history",
    'apps.quotation',
    'apps.invoice_designer',
    'apps.reports',
    "apps.dashbaord",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production (after SecurityMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.myglobal.authentication_middleware.loginrequiredmiddleware',
    'apps.myglobal.authentication_middleware.AutoLogoutMiddleware',
    "simple_history.middleware.HistoryRequestMiddleware",
]



ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.myglobal.context_processors.dynamic_js_urls.dynamic_js_urls',
                'apps.myglobal.context_processors.user_perms.user_perms',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {"console": {"class": "logging.StreamHandler"}},
#     "loggers": {
#         "django.db.backends": {"level": "DEBUG", "handlers": ["console"]},
#     },
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#  SHOW VARIABLES LIKE 'skip_name_resolve'; > this should be ON for better connection speed in mysql.ini
_db_engine = _cfg.get('database', 'engine', fallback='django.db.backends.mysql')
_db_name   = _cfg.get('database', 'name',   fallback='generalsoft-laragon')
_db_user   = _cfg.get('database', 'user',   fallback='root')
_db_pass   = _cfg.get('database', 'password', fallback='')
_db_host   = _cfg.get('database', 'host',   fallback='127.0.0.1')
_db_port   = _cfg.get('database', 'port',   fallback='3306')

if _db_engine  == 'django.db.backends.sqlite3':
    # SQLite: name is a file path resolved relative to exe dir
    _db_path = _path('database', 'name', fallback='db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': str(_db_path),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': _db_name,
            'USER': _db_user,
            'PASSWORD': _db_pass,
            'HOST': _db_host,
            'PORT': _db_port,
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                'connect_timeout': 10,
                'read_timeout': 30,
                'write_timeout': 30,
                # Enable compression for large data
                'compress': True,
                # SSL if needed (can add latency)
                'ssl': False
            },
        },
        'punjab_taxila': {
            'ENGINE': _db_engine,
            'NAME': "punjab_taxila",
            'USER': _db_user,
            'PASSWORD': _db_pass,
            'HOST': _db_host,
            'PORT': _db_port,
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                'connect_timeout': 10,
                'read_timeout': 30,
                'write_timeout': 30,
                # Enable compression for large data
                'compress': True,
                # SSL if needed (can add latency)
                'ssl': False
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = _cfg.get('django', 'time_zone', fallback='Asia/Karachi')

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    _path('paths', 'staticfiles_dirs', fallback='static'),
]

# STATIC_ROOT: where 'collectstatic' puts files; WhiteNoise serves from here in production.
STATIC_ROOT = _path('paths', 'static_root', fallback='staticfiles')

# WhiteNoise compressed static file storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = _path('paths', 'media_root', fallback='media')

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'

SESSION_COOKIE_AGE = 1800
