# Generated by Django 6.0.7 on 2026-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pos_invoice', 'POS Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('credit_sale_invoice', 'Credit Sale Invoice'), ('quotation', 'Quotation'), ('voucher', 'Voucher'), ('barcode_label', 'Barcode Label')], max_length=32)),
                ('page_type', models.CharField(choices=[('thermal_58', 'Thermal 58mm'), ('thermal_80', 'Thermal 80mm'), ('a5', 'A5'), ('a4', 'A4')], max_length=16)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled page types are hidden from preview, print selection and are never rendered.')),
                ('is_default', models.BooleanField(default=False, help_text='The template used when no explicit template_id is given for this document_type + page_type combination.')),
                ('name', models.CharField(default='Default', max_length=120)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', 'page_type', '-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'page_type', 'name'), name='unique_template_per_document_page_name')],
            },
        ),
    ]
