# Generated by Django 6.0.1 on 2026-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateconfiguration',
            name='invoice_language',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu'), ('bilingual', 'Bilingual (English + Urdu)')], default='english', help_text='Choose Urdu or Bilingual to enable Nastaleeq font and RTL layout.', max_length=16),
        ),
        migrations.AlterField(
            model_name='templateconfiguration',
            name='page_type',
            field=models.CharField(choices=[('thermal_58', 'Thermal 58mm'), ('thermal_80', 'Thermal 80mm'), ('a5', 'A5'), ('a4', 'A4'), ('urdu_80mm', 'Thermal 80mm — Urdu'), ('urdu_58mm', 'Thermal 58mm — Urdu'), ('urdu_a4', 'A4 — Urdu'), ('urdu_a5', 'A5 — Urdu'), ('bilingual_a4', 'A4 — Bilingual'), ('bilingual_80mm', 'Thermal 80mm — Bilingual')], max_length=16),
        ),
    ]
