# Generated by Django 6.0.1 on 2026-08-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDbSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=150)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'branch', 'model_name'], name='myglobal_lo_company_7fde1d_idx')],
            },
        ),
    ]
