# Generated by Django 6.0.1 on 2026-06-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default=None, max_length=255)),
                ('alias_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ws_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('ws_disc_per', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('last_pur_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('base_disc_per', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('min_base_sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('carton_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('carton_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('carton_disc_per', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('dzn_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('dzn_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('dzn_disc_per', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('manualbc', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('barcode2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('reorder', models.IntegerField(blank=True, default=None, null=True)),
                ('product_location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('remaining_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('sold_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('purchase_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itembrand')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcategory')),
                ('manufacturer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcompany')),
                ('subcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemsubcategory')),
                ('base_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_inv', to='inventory.unit')),
                ('carton_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carton_inv', to='inventory.unit')),
                ('dzn_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dzn_inv', to='inventory.unit')),
            ],
        ),
    ]
