# Generated by Django 6.0.1 on 2026-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['barcode'], name='idx_inventory_barcode'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['manualbc'], name='idx_inventory_manualbc'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['inv_id'], name='idx_inventory_inv_id'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['prod_name'], name='idx_inventory_prod_name'),
        ),
    ]
