# Generated by Django 6.0.1 on 2026-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_idx_inventory_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='salesman_commission',
            field=models.IntegerField(blank=True, default=0, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
