# Generated by Django 6.0.1 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_salesman_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='salesman_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
