# Generated by Django 6.0.1 on 2026-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_salesman_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bal_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
