# Generated by Django 6.0.1 on 2026-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_companyconfiguration_options_and_more'),
        ('inventory', '0006_inventory_bal_qty'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_barcode',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_manualbc',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_inv_id',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='idx_inventory_prod_name',
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'barcode'], name='idx_inv_comp_bar'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'manualbc'], name='idx_inv_comp_mbc'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'barcode2'], name='idx_inv_comp_b2'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'inv_id'], name='idx_inv_comp_invid'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'alias_name'], name='idx_inv_comp_alias'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'prod_name'], name='idx_inv_comp_prod'),
        ),
    ]
