# Generated by Django 6.0.1 on 2026-09-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventory_idx_inventory_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
