# Generated by Django 6.0.1 on 2026-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='max_stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
