# Generated by Django 6.0.1 on 2026-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_max_stock_inventory_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='prod_name_ur',
            field=models.CharField(blank=True, default=None, help_text='آئٹم کا اردو نام — Nastaleeq font will be used in Urdu/Bilingual invoices.', max_length=500, null=True, verbose_name='Urdu Item Name'),
        ),
    ]
