# Generated by Django 6.0.1 on 2026-09-30 16:05

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_prod_name_ur'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='prod_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.inventory.models.product_image_path),
        ),
        migrations.AddField(
            model_name='inventory',
            name='prod_picture_thumb',
            field=models.ImageField(blank=True, help_text='Auto generated 150x150 webp', max_length=500, null=True, upload_to=apps.inventory.models.product_image_path),
        ),
    ]
