# Generated by Django 6.0.1 on 2026-10-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_branch_address_ur_branch_name_ur_company_address_ur_and_more'),
        ('inventory', '0011_inventory_image_updated_at_inventory_prod_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, null=True)),
                ('item', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pack_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('net_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adj_type', models.CharField(choices=[('OPENING', 'Opening'), ('DESTROYED_EXPIRED', 'Destroyed/Expired'), ('SAMPLE_GIVEN', 'Sample Given'), ('BREAKAGE_LEAKAGE', 'Breakage/Leakage'), ('THEFT_SHORTAGE', 'Theft/Shortage'), ('EXCESS_FOUND', 'Excess Found'), ('CORRECTION', 'Correction')], max_length=50)),
                ('acc_code', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(db_index=True)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemsubcategory')),
            ],
            options={
                'db_table': 'stock_adjustment',
                'indexes': [models.Index(fields=['company', 'voucher_no'], name='stock_adjus_company_9d1371_idx'), models.Index(fields=['company', 'date'], name='stock_adjus_company_20cb4f_idx')],
            },
        ),
    ]
