# Generated by Django 6.0.1 on 2026-10-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_companyconfiguration_stock_valuation_method'),
        ('inventory', '0012_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity', models.DecimalField(db_column='qty', decimal_places=3, max_digits=12)),
                ('rate_cost_per_unit', models.DecimalField(db_column='unit_cost', decimal_places=4, max_digits=12)),
                ('net_value', models.DecimalField(db_column='value', decimal_places=2, max_digits=15)),
                ('voucher_type', models.CharField(db_column='ref_type', db_index=True, max_length=20)),
                ('voucher_bill_no', models.IntegerField(db_column='ref_id', db_index=True)),
                ('voucher_row_id', models.BigIntegerField(db_column='ref_line_id', null=True)),
                ('voucher_date', models.DateField(db_column='date', db_index=True)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_ledger',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(db_column='qty_received', decimal_places=3, max_digits=12)),
                ('quantity_remaining', models.DecimalField(db_column='qty_remaining', db_index=True, decimal_places=3, max_digits=12)),
                ('rate_cost_per_unit', models.DecimalField(db_column='unit_cost', decimal_places=4, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', db_index=True, null=True)),
                ('receipt_date', models.DateField(db_column='receipt_date', db_index=True)),
                ('source_voucher_type', models.CharField(db_column='source_type', db_index=True, max_length=20)),
                ('source_bill_no', models.IntegerField(db_column='source_id', db_index=True)),
                ('source_row_id', models.BigIntegerField(db_column='source_line_id', null=True)),
                ('dateent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_lot',
            },
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='stock_adjus_company_9d1371_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='stock_adjus_company_20cb4f_idx',
        ),
        migrations.AddField(
            model_name='stockledger',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='inventory_item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='inventory_item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='stock_lot',
            field=models.ForeignKey(db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot'),
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='subcategory',
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['company', 'branch', 'inventory_item', 'receipt_date', 'id'], name='idx_lot_fifo'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['company', 'branch', 'inventory_item', 'expiry_date', 'receipt_date'], name='idx_lot_fefo'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['voucher_type', 'voucher_bill_no'], name='idx_led_voucher'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['company', 'branch', 'inventory_item', 'voucher_date'], name='idx_led_item_date'),
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
