# Generated by Django 6.0.1 on 2026-10-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockledger_stocklot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='adj_type',
            field=models.CharField(blank=True, db_column='adj_type', default='', max_length=20, null=True),
        ),
    ]
