# Generated by Django 6.0.1 on 2026-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockledger_adj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='acc_code',
            field=models.IntegerField(blank=True, db_column='acc_code', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='acc_code',
            field=models.IntegerField(blank=True, db_column='acc_code', db_index=True, null=True),
        ),
    ]
