# Generated by Django 6.0.1 on 2026-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockledger_acc_code_stocklot_acc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='batch_no',
            field=models.CharField(blank=True, db_column='batch_no', db_index=True, max_length=50, null=True),
        ),
    ]
