# Generated by Django 6.0.1 on 2026-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockledger_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='batch_no',
            field=models.CharField(blank=True, db_column='batch_no', db_index=True, max_length=50, null=True),
        ),
    ]
