# Generated by Django 6.0.4 on 2026-04-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_branch_address_branch_email_branch_license_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_disc_percent_bill', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('promotion_disc_percent_item', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
        ),
    ]
