# Generated by Django 6.0.4 on 2026-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_companyconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfiguration',
            name='credit_sale_receipt_size',
            field=models.CharField(choices=[('Thermal', 'Thermal'), ('A4', 'A4'), ('A5', 'A5')], default='Thermal', max_length=10),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='multiple_bill_prints',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='pos_sale_receipt_size',
            field=models.CharField(choices=[('Thermal', 'Thermal'), ('A4', 'A4'), ('A5', 'A5')], default='Thermal', max_length=10),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='purchase_receipt_size',
            field=models.CharField(choices=[('Thermal', 'Thermal'), ('A4', 'A4'), ('A5', 'A5')], default='Thermal', max_length=10),
        ),
    ]
