# Generated by Django 6.0.4 on 2026-04-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_companyconfiguration_credit_sale_receipt_size_and_more'),
    ]

    operations = [
    ]
