# Generated by Django 6.0.4 on 2026-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='created_at',
            new_name='dateent',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='dateent',
        ),
        migrations.RenameField(
            model_name='companyconfiguration',
            old_name='created_at',
            new_name='dateent',
        ),
        migrations.RenameField(
            model_name='posterminal',
            old_name='created_at',
            new_name='dateent',
        ),
    ]
