# Generated by Django 6.0.1 on 2026-09-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_rename_created_at_branch_dateent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={'verbose_name': 'Company Configuration', 'verbose_name_plural': 'Company Configurations'},
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='config_data',
            field=models.JSONField(blank=True, default=dict, help_text="Module-wise JSON configuration: {'pos': {...}, 'purchase': {...}, 'quotation': {...}, 'inventory': {...}, 'general': {...}}"),
        ),
        migrations.AlterUniqueTogether(
            name='companyconfiguration',
            unique_together={('company', 'branch')},
        ),
        migrations.CreateModel(
            name='DefaultAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_data', models.JSONField(blank=True, default=dict, help_text="Key-value mapping of default accounts: {'cash_client_acc': 112000001, 'sales_counter_acc': 110000001, ...}")),
                ('dateent', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.company')),
            ],
            options={
                'verbose_name': 'Default Accounts Configuration',
                'verbose_name_plural': 'Default Accounts Configurations',
                'unique_together': {('company', 'branch')},
            },
        ),
    ]
