# Generated by Django 6.0.1 on 2026-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_companyconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
