# Generated by Django 6.0.1 on 2026-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_company_license_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_ur',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address (Urdu)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_ur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ur',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address (Urdu)'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='company',
            name='ntn_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NTN Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='ntn_no_ur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NTN Number (Urdu)'),
        ),
    ]
