# Generated by Django 6.0.1 on 2026-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_branch_address_ur_branch_name_ur_company_address_ur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfiguration',
            name='stock_valuation_method',
            field=models.CharField(choices=[('FIFO', 'FIFO (First In, First Out)'), ('FEFO', 'FEFO (First Expired, First Out)'), ('LIFO', 'LIFO (Last In, First Out)'), ('AVERAGE', 'Weighted Average Cost'), ('LAST_PUR_PRICE', 'Last Purchase Price')], default='LAST_PUR_PRICE', help_text='Stock valuation method for COGS and inventory lot consumption', max_length=20),
        ),
    ]
